### ISSUE TITLE
Using maps in for loops

### ISSUE THREAD

**Issue by idontusenumbers** [mbosecke/pebble#100]
The docs indicate you can use maps in for loops but there are no examples. For the time being I'm using map.values.

**Comment by realcnbs** [comment]
Yeah such syntax would be great to have:
```
{% for key,value in map %}
```

**Comment by mbosecke** [comment]
The syntax for iterating over a map is as follows:

    {% for entry in map %}
      {{ entry.key }} - {{ entry.value }}
    {% endfor %}

The documentation is definitely needing an update; I'm doing that right now. Thanks.

**Comment by idontusenumbers** [comment]
Awesome, thanks!
