### ISSUE TITLE
Safe list access

### ISSUE THREAD

**Issue by cjalmeida** [mbosecke/pebble#101]
When accessing list by index (ie. "item[3]"), if the index does not exists, it throws a java.lang.IndexOutOfBoundsException, instead of the expected behavior of returning "null".

A simple try/catch at line 103 of GetAttributeExpression should work.

**Comment by mbosecke** [comment]
I like this idea but only if it still throws an error if the user sets the "strictVariables" setting. In that case it should actually wrap the IndexOutOfBoundsException with a PebbleException that contains the line number. 

We would also want to implement the same for accessing lists by index (a few lines down in the same GetAttributeExpression class).

**Comment by mbosecke** [comment]
Would you like to submit a pull request for this one?
