### ISSUE TITLE
Don't fail on too high toIndex in slice filter

### ISSUE THREAD

**Issue by realcnbs** [mbosecke/pebble#105]
This will throw an exception if popularPost size lower than 7.
```
{% for popularPost in popularPosts|slice(0,6) %}
```
This requires adding collection length checking logic in the template like this:
```
{% if popularPosts.size < 7 %}
    {% set sliceTo = popularPosts.size - 1 %}
{% else %}
    {% set sliceTo = 6 %}
{% endif %}
{% for popularPost in popularPosts|slice(0,sliceTo) %}
```
I think It should silently return all the elements available.

**Comment by realcnbs** [comment]
This one makes it a bit less strict. But in my case template developers usually don't know / cannot be sure of the list length. Instead they just follow visual design. And for example in one of the cases we had 10 slice filters in a single page and adding length checks to each of them just feels wrong.
An option could be introducing a new filter.

**Comment by mbosecke** [comment]
I'm very hesitant to change the current implementation. It's already hard enough to sell a non-type safe templating language to Java developers as it is; most of the feedback I get is to make it even stricter.

My recommendation would be to write a custom filter that is used in your app that is less strict than the default implemention. Either that or use a ternary operation to make your code more succinct; something like this:

    {% set popularPost = popularPosts.size > 7 ? popularPosts.slice(0, 7) : popularPosts %}
    {% for post in popularPosts %}
      ...
    {% endfor %}

**Comment by realcnbs** [comment]
I see. And including a less strict filter with a different name into core is not an option too?

**Comment by mbosecke** [comment]
I'm not a fan of that idea. It's a slippery slope that could leads to lots of different variations of the same basic functionality all with differing strictness. I would rather our efforts go into promoting and making it easier for users to extend Pebble with their own [custom filters](http://mitchellbosecke.com/pebble/documentation/guide/extending-pebble) (which is already fairly easy to do).

**Comment by realcnbs** [comment]
Ok great, thanks for the feedback!

**Comment by mbosecke** [comment]
And I'm also planning on setting up a github repository that can be used to share community developed extensions.

Regardless, I appreciate your efforts. Any more ideas are always welcome here.

**Comment by realcnbs** [comment]
Thanks, regarding making it easier to extend check this one - #107
