### ISSUE TITLE
Type safe functions/filters/tests

### ISSUE THREAD

**Issue by realcnbs** [mbosecke/pebble#107]
Coming from jtwig I was missing type safe functions as well as defining multiple function in a single class with allowing function polymorphism.
An example how it could be done:
```
@PebbleFunction(name = "thumb", aliases = {"imageThumb"})
public Media thumb(@Parameter Media media, @Parameter Integer targetWidth, @Parameter Integer targetHeight) {
   ...
}

@PebbleFunction(name = "thumb", aliases = {"imageThumb"})
public Media thumb(@Parameter Media media, @Parameter Integer targetWidth, @Parameter Integer targetHeight, @Parameter Boolean cropped) {
   ...
}

```
So here you can define a function with the same name but diff combination of parameters count and types. Also type safe parameters is a huge advantage as you don't have to manually do type conversions inside the functions.
Though I am not sure about defining function name/aliases at the implementation level rather than extension configuration level, not sure which is better.

**Comment by mbosecke** [comment]
I'm a big fan of this idea

**Comment by cy6erGn0m** [comment]
AFAIK the parameter names are not available in runtime, isn't it?

**Comment by realcnbs** [comment]
Why they are needed? Having strict parameter order is enough.

**Comment by cy6erGn0m** [comment]
The API doesn't provide ability to omit parameter names for now

**Comment by realcnbs** [comment]
Well, i'm not sure what you mean then )

**Comment by mbosecke** [comment]
I took a stab at implementing this and it quickly unraveled into much more work than I expected. I'm going to close this for now because I don't think it's quite worth the effort. I am still a fan of the idea and would be open to a pull request or perhaps I'll revisit this again in the future.
