### ISSUE TITLE
Meta Documentation

### ISSUE THREAD

**Issue by thomashunziker** [mbosecke/pebble#110]
The documentation of the filters, tests, tags etc. are currently somehow generated by some Jekyll script / template.

Since we are extending the Pebble heavily by our own extensions it would be helpful when we are able to generate the documentation based on the currently added filters, tags etc. I have not thought in detail how I would achieve this. Some options:
* Add some Java annotation to the classes which contains the documentation about them.
* Add some methods to the interface which contains the documentation.

I saw the first approach in this project: https://github.com/HubSpot/jinjava

My questions regarding this topic:
* How is currently the process to generate the documentation? Is there any git repository with the documentation snippets?
* Would a reflective approach as described above of any interest?

**Comment by mbosecke** [comment]
All the pebble documentation is currently hand written in some sloppy, poorly organized java app which I've been planning on re-writing from scratch. I'd like to get it into a respectable state that I don't mind publishing so I can start to receive pull requests for it. 

I don't think I'm a big fan of the custom java annotations idea though. It just seems like a lot of work without enough value. I don't know a lot about javadocs and it's capabilities but I suspect it may provide a similar functionality without having to reinvent the wheel.

But honestly, I don't know which direction I'll be going with the documentation. I need to do more research and see how other people do it.

**Comment by thomashunziker** [comment]
We have discus this issue also internally. Annotations are not good, because you really don't want to write the documentation in annotation (line breaks etc. are horrible in Java code). 

Using some additional methods on the interfaces for documentation is also not really an option because you want to generate the documentation during the publishing / build process. Calling the methods on the objects is hard in the build process.

We came also to the conclusion that the Java Doc is also not an option, because you typically want to reserve the Java Doc for documentation of the code itself. The documentation we are talking about here is for the web designer / template creator, but not for the developer of Pebble. So a clear separation between the documentation of the code and the API documentation is required.

The approach we think would work is to put the documentation on the class path. Based on some naming convention the documentation can be resolved. E.g. 

* /doc/pebble/tags/block.adoc
* /doc/pebble/tags/include.adoc
* /doc/pebble/filter/replace.adoc
* /doc/pebble/filter/replace/replacements.adoc

E.g. we put for each filter, tag etc. a file on the class path. Additionally for each argument we add a file on the class path. 

The advantage is we can ship the documentation also along with the code and it can be reused. On the other hand it can be used to extract the documentation during the build process. Eventually we need to create a custom Maven Plugin (eventually it would be better to use gradle in this case).

With ASCII Doc we can put some meta information into the documentation file to add more information if this is required. ASCII Doc can be easily rendered in Java with http://asciidoctor.org/docs/asciidoctorj/

**Comment by thomashunziker** [comment]
From our side we need anyway a solution. If you like I can create a merge request with our implementation and you can decide if you like the approach or not. Since we need the documentation during the runtime their will be no build tool / maven plugin. However the extraction etc. can be eventually reused.

**Comment by mbosecke** [comment]
I don't think I'm going to go forward with any changes to the documentation at this time. I'll probably be revisiting this at a later time.
