### ISSUE TITLE
Pass an expression to a macro

### ISSUE THREAD

**Issue by r0b0tbuilder** [mbosecke/pebble#123]
It could be useful to pass an expression as an argument to a macro, instead of just passing a literal value (such as a literal string).  The following is an example of how this feature may be useful.

```javascript
{% macro textarea(type, name, value, disabled=false) %}
  <textarea type="{{ type }}" name="{{ name }}" value="{{ value }}" hidden="{{ disabled }}">
{% endmacro %}

<html>
  ...
  <body>
    ...
    {{ textarea("text", "comment", "Post your comment here...", {{ not(databaseEnabled) }}) }}
  </body>
</html>
```
In the above example, the usage of ```textarea``` macro takes advange of this feature to only create a comment text area if the database is enabled for this web application.  Specifically, the comments section will only be hidden if ```databaseDisabled``` is set to ```true```.

**Comment by thomashunziker** [comment]
I think you can simply change it to:
```
{% textarea("text", "comment", "Post your comment here...", databaseEnabled) %}
```
Have you tried that?

**Comment by r0b0tbuilder** [comment]
Never mind.  It appears that @thomashunziker is correct.  The variable can be directly passed.
