### ISSUE TITLE
improvement: retrieve current locale used

### ISSUE THREAD

**Issue by jmsanzg** [mbosecke/pebble#127]
Sometimes the translations are not in a resource bundle but in the beans themselves. For instance, imagine an Article which may have a name translated to multiple languages. The best way to handle this would be to have the locale parameter available directly on the template.

**Comment by ebussieres** [comment]
If you are using pebble-spring3, I have just maded a pull request (https://github.com/mbosecke/pebble-spring3/pull/5) to access the current locale.

**Comment by jmsanzg** [comment]
@ebussieres that looks amazing!. Sadly I'm using Pebble calling it directly to generate an email from a template. I'll check your commit and I can try to pull the same functionality for no-spring use.

**Comment by ebussieres** [comment]
You can just create a simple function like this

```java
public class LocaleFunction implements Function {
    @Override
    public Object execute(Map<String, Object> args) {
        EvaluationContext context = (EvaluationContext) args.get("_context");
        return context.getLocale();
    }

    @Override
    public List<String> getArgumentNames() {
        return null;
    }
}
```

**Comment by jmsanzg** [comment]
I'll use that function and, if I can vote, I'd put it on the core list of available functions.

**Comment by mbosecke** [comment]
Added a global variable called "locale" in commit 4862f9d. It can be accessed just like any other user-provided variable:

```
<html>
    <body>
        <p>The current locale is: {{ locale }}</p>
    </body>
</html>
```
