### ISSUE TITLE
improvement: allow variables to be put inside square brackets

### ISSUE THREAD

**Issue by jmsanzg** [mbosecke/pebble#128]
Currently only numbers and strings are allowed inside square brackets. Could be great to be able to retrieve an element based on a variable too.

For instance something like

    {{ myMap[myVar].attribute }}

**Comment by donnior** [comment]
Agree and wish Pebble could have more power EL , or integrate other EL engine such Ognl, MVEL to it?

**Comment by mbosecke** [comment]
It was a good idea, thanks.
