### ISSUE TITLE
Character encoding issue

### ISSUE THREAD

**Issue by gbanda** [mbosecke/pebble#154]
Hi,

While using Pebble I have encountered an issue where a word like "add'tl" is encoded to "add#39;tl" after template evaluation. How to fix this? Test code is below.

@Test
    public void testTemplate() throws Exception {
        PebbleTemplate template = pebbleEngine.getTemplate("{{msg1}}");
        StringWriter writer = new StringWriter();
        template.evaluate(writer, Collections.singletonMap("msg1", "Hello add'tl"));
        System.out.println(writer);

    }

Actual result : Hello add\&#39;tl
Expected result : Hello add'tl
Any help would be much appreciated.

**Comment by ebussieres** [comment]
It's not an encoding problem, it's the autoescaping filter. You should read the escaping section of the doc here : http://www.mitchellbosecke.com/pebble/documentation/guide/basic-usage

You can use {{msg1 | raw}} if you don't want to escape it (http://www.mitchellbosecke.com/pebble/documentation/filter/raw)

**Comment by gbanda** [comment]
thanks a lot, I will try and post back
