### ISSUE TITLE
A pair of additions to ScopeChain would be really handy

### ISSUE THREAD

**Issue by hectorlf** [mbosecke/pebble#156]
I'm working on an extension to add support for Joda Time and I've run into this use case:
- You have a series of dates that you want to format with a specific pattern (eg. a table of dates)
- There's a default pattern that's different from the one you want for that dates
- You use the provided {%jodaPattern "es"%}...{%endJodaPattern%} block-like tag
- Happiness and joy

My current code pushes a scope just to store the pattern so it will be able to pop it out when tag finishes. But, if some nested tag pushes a scope and doesn't pop it, I won't be able to pop mine, leading to unpredictable side effects.

Another approach would be to skip the scope push (or doing it only when necessary), but then I'd need a way to clear the attributes I put (something like ScopeChain.remove(key)).

Oh, and while we're at it, there's another thing needed: to be able to get a reference to a concrete scope, not the entire chain (something like ScopeChain.pushScope() returns a Map)

As always, I volunteer to provide a PR. What do you think?

**Comment by mbosecke** [comment]
The second request of having `pushScope()` returning the newly added Scope sounds reasonable to me.

I don't fully understand the first problem though. I think you're doing the correct thing by pushing your own scope and then popping it when you are done with it, but why would a nested tag not pop a scope that it pushed? Wouldn't this be a bug with the nested tag?

**Comment by hectorlf** [comment]
I'd say yes, that should be a bug. At the moment I just try to identify the error condition and issue a logger.warn.

On a second thought, I may have been too much of an overthinker. Lets close this until a real issue comes up :+1:
