### ISSUE TITLE
Confusing "Functions" documentation

### ISSUE THREAD

**Issue by nanodeath** [mbosecke/pebble#157]
On http://www.mitchellbosecke.com/pebble/documentation/guide/extending-pebble, the following line is present in the "Functions" section:

> First and foremost, it's important to understand the different intentions behind a function and a filter because it can often be ambiguous which one should be implemented. A **`filter`** is intended to modify existing content where a **`filter`** is moreso intended to produce new content. 

(emphasis mine)

One of those should probably be `function`...but I don't know which one.

**Comment by hectorlf** [comment]
Function creates new content, Filter modifies existing content. Hope it helps!

**Comment by nanodeath** [comment]
Yeah, so the second `filter` in the document should actually be `function`, then.

**Comment by mbosecke** [comment]
Fixed; thanks.
