### ISSUE TITLE
parallel blocks don't have access to macros imported into outer context

### ISSUE THREAD

**Issue by karlpauls** [mbosecke/pebble#159]
I'm not sure this is by design or not (I would find it somewhat surprising if it is by design) but if you have something like:

> {% import "macros.pebble" %}
> 
> {% parallel %}
>    do something involving a macro from macros.pebble 
> {% endparallel %}

it fails because the macro is not found. Furthermore, it will continue to write out content from after the block and only throw an exception at the end (i.e., when the rest is already flushed out.)

I can make it work by always including the marcos again inside all parallel blocks i.e.,:

> {% import "macros.pebble" %}
> 
> {% parallel %}
> {% import "macros.pebble" %}
>    do something involving a macro from macros.pebble 
> {% endparallel %}

but this is somewhat cumbersome as I keep forgetting about it and it seems like the parallel context should inherit macros from the outer context. It is possible that I did something else wrong in my pebble integration so if this is not intended I can go back and try to boil it down to a simple failing set-up but I wanted to ask first: Is there a design reason for this behavior (the documentation doesn't seem to mention anything about it)?

**Comment by hectorlf** [comment]
Just chiming in to say that it seems like a bug. Parallel tag creates a copy of the EvaluationContext with and empty list of imports.

**Comment by mbosecke** [comment]
Yup, this sounds like a bug to me.
