### ISSUE TITLE
Augment ConcatenateExpression to allow array, list and map parameters

### ISSUE THREAD

**Issue by hectorlf** [mbosecke/pebble#164]
I was adapting my templates when I found a use case where fusing two maps would've been handy. I remember there was something in the + operator, but it actually only adds Lists.

I'm not keen on overloading +, so what about adding the support to ~? Want a PR?

**Comment by mbosecke** [comment]
To be honest, I kind of regret implementing string concatenation with the ~ character. It just isn't a very java-like operator. 

I think a "map fuse" feature should be implemented as a filter instead. The ability to chain filters together reminds me of java 8 streams and I'd like to head more in that direction. The twig library uses a [merge filter](http://twig.sensiolabs.org/doc/filters/merge.html) but I'd be open to other names.

**Comment by hectorlf** [comment]
A quick google search shows merge to be a common name for that operation. I'm really bad at making up names, but other options are... hmmm... combine, concat, fuse, copy... I'm good with merge, anyway.
