### ISSUE TITLE
for-loop with interface type

### ISSUE THREAD

**Issue by NoizeMe** [mbosecke/pebble#166]
I had a problem with for-loops that iterate over an interface type. The parser just takes the concrete type of the first element and assumes that all other elements have the same type, which leads to a ClassCastException.

Is there a reasonable workaround, is it a bug or is it just the way pebble is intended to work?

With kind regards

**Comment by mbosecke** [comment]
Sounds like a bug to me. Can you provide a stack trace or an example I can use to replicate this?

**Comment by NoizeMe** [comment]
I just noticed that the pebble integration for spark uses pebble 1.4.4, but with pebble 2.0.0 my test-code works just fine. I am sorry that I did not check that beforehand, I just assumed spark would not ship with an outdated version.

Anyway for the sake of completeness the code for reproduction:
**App.java**
```Java
public class App {

	static interface Interface {
		String getString();
	}

	static class A implements Interface {
		public String getString() {
			return "A";
		}
	}

	static class B implements Interface {
		public String getString() {
			return "B";
		}
	}

	public static void main(final String[] args) throws PebbleException, IOException {
		List<Interface> entries = new ArrayList<Interface>();
		entries.add(new A());
		entries.add(new B());

		Map<String, Object> attributes = new HashMap<String, Object>();
		attributes.put("entries", entries);

		StringWriter writer = new StringWriter();

		PebbleEngine engine = new PebbleEngine.Builder().build();
		engine.getTemplate("test.pebble").evaluate(writer, attributes);

		System.out.println(writer.toString());
	}

}
```

**test.pebble**
```
{% for e in entries %}
	{{ e.string }}
{% endfor %}
```

In 1.4.4 the bug is present, but it seems it is already fixed. That is actually really good to know, because pebble is now an options for us again :).

**Comment by mbosecke** [comment]
Glad to hear! Thanks for being thorough.
