### ISSUE TITLE
templating bootstrap components

### ISSUE THREAD

**Issue by zepernick** [mbosecke/pebble#167]
Nice work on this project.  Could you tell me how this might work with templating bootstrap components?  Can you use jsp and use jsp tags for form controls, or would you recommend building out custom tags in pebble for handling this.  I am also considering whether to use Struts2 with Spring or straight spring mvc.  Has anyone integrated this project with Struts 2?

**Comment by hectorlf** [comment]
Spring Mvc support is far from complete, there's a few tags implemented in pebble-spring3 project but many are missing.

AFAIK, there's no extension for Struts 2 (in GitHub at least). I had plans for it, but haven't started yet. It's not difficult, though, but tedious. (self advertising here: If you want to take a shot at it, I have an integration with Stripes Framework at my account that you can use as a foundation for the Struts 2 one)

Regarding bootstrap, I didn't even know that people were abstracting it's html into jsp tags, and I'm really not sure if I like it or not :S. I'm supposing you refer to something like this project: https://github.com/Mrdigs/Bootstrap.jsp
There's no way of mixing jsp and Pebble in the same template, so you'd have to implement that functionality as a custom Pebble extension.

**Comment by zepernick** [comment]
Thank you very much for the feedback.
