### ISSUE TITLE
Customize delimiters

### ISSUE THREAD

**Issue by gahissy** [mbosecke/pebble#171]
Is it possible to change the default delimiters: `{{ }}` ?

**Comment by mbosecke** [comment]
In theory, yes, although I don't think it's within the scope of our unit tests nor is it a documented feature. I'll point you to some code within Pebble to get you started:

* [Create a `Syntax` object using the builder pattern](https://github.com/mbosecke/pebble/blob/master/src/main/java/com/mitchellbosecke/pebble/lexer/Syntax.java#L170)
* [Provide the `Syntax` object when creating the `PebbleEngine` object.](https://github.com/mbosecke/pebble/blob/master/src/main/java/com/mitchellbosecke/pebble/PebbleEngine.java#L310) 

If you do go forward with it; let me know how it works it.
