### ISSUE TITLE
Macro with children

### ISSUE THREAD

**Issue by gahissy** [mbosecke/pebble#172]
Is it possible to update the documentation to show how to write macros with body/children ?

```
{% macro form(action, class) %}
    <form class="{{ class }}" role="form" action="{{ action }}" novalidate="novalidate">
        {{ body }}
    </form>
{% endmacro %}
```

**Comment by mbosecke** [comment]
Macros do not support inheritance. Either you need to provide the "body" via an argument to the macro or instead of macros use the `include` tag to include a full fledged template which does support inheritance.

    {% include 'child.html' with { 'action' : 'post', 'class' : 'myclass'} %}

and the base form template, `form.html`:
```
<form class="{{ class }}" role="form" action="{{ action }}" novalidate="novalidate">
  {{ body }}
</form>
```

and a child form template, `child.html`:
```
{% extends 'form.html' %}
{% block body %}
   This is the body.
{% endblock %}
```
