### ISSUE TITLE
Issue iterating over maps

### ISSUE THREAD

**Issue by MikeBull94** [mbosecke/pebble#55]
I have a `Map<Integer, List<Article>>` where `Article` is an object with two strings (name, title) and the integer is the year of publication.

I can iterate over the years like so:

```HTML+Django
{% for year in articles.keySet %}
	<h2>{{ year }}</h2>
{% endfor %}
```

However there is then no way to select the list of articles based on the year.

If I try:

```HTML+Django
{% for year in articles.keySet %}
	<h2>{{ year }}</h2>
	{% for article in articles[year] %}
		<p>{{ article.title }}</p>
	{% endfor %}
{% endfor %}
```

It takes the `year` as a string literal, thus tries to find a method named `year` in the HashMap class.

Please can you address this with some ability to pass variables or something?

Thanks.

**Comment by MikeBull94** [comment]
I've found a workaround by creating a wrapper class that contains a `year` and a `List<Article>` then iterating over a list of these wrapper classes, however this is quite a hacky workaround.

**Comment by nhylated** [comment]
@MikeBull94 there's no need for creating a separate wrapper class. You can iterate over `article.entrySet` and for each entry, use `entry.key` to get the year and `entry.value` to get the list of articles.

I've demonstrated this with an example in [this](https://gist.github.com/nhylated/a148ad6e939cdc6fa699) gist.

**Comment by MikeBull94** [comment]
Ah that's a much more elegant solution. Thanks very much.

**Comment by mbosecke** [comment]
Thanks @nhylated
