### ISSUE TITLE
Android incompatibility with Character.isAlphabetic()

### ISSUE THREAD

**Issue by mbosecke** [mbosecke/pebble#63]
It was reported in the [google group](https://groups.google.com/forum/#!topic/pebble-templating-engine/Ep-9HjpRnoc) that the use of this static method is preventing the use of pebble on the android platform (api version < 4.4).

**Comment by SubOptimal** [comment]
`Character.isAlphabetic(codePoint)` can be substituted by 
`Character.isLetter(codePoint) || Character.getType(codePoint) == Character.LETTER_NUMBER`

isAlphabetic is true for characters of unicode category
- UPPERCASE_LETTER
- LOWERCASE_LETTER
- TITLECASE_LETTER
- MODIFIER_LETTER
- OTHER_LETTER
- LETTER_NUMBER 

isLetter is true for characters of unicode category
- UPPERCASE_LETTER
- LOWERCASE_LETTER
- TITLECASE_LETTER
- MODIFIER_LETTER
- OTHER_LETTER

So the remaining check is for category LETTER_NUMBER which is fulfilled with `getType(codePoint)`

cheers
Frank

**Comment by mbosecke** [comment]
Thanks a lot!
