### ISSUE TITLE
ArgumentsNode should honor arguments' name if present in a multi-arg function invocation

### ISSUE THREAD

**Issue by hectorlf** [mbosecke/pebble#65]
Currently, when argumentNames list is null, argument names (if present) are discarded if favor of an int. This makes it impossible to relate argument values with their "meaning".

My use case: i'm working on an extension to integrate Pebble with Stripes Framework (basically, a rip-off of their jsp tags), and one of the key tags builds a url from an action. Action urls may be parameterized with up to 9 params (IIRC), keyed by a string. Eg. /archive/{year}/{month}/{name}.action
To replay that functionality, i need a multi-arg function that retains the names of the arguments to be able to build the proper url.

**Comment by mbosecke** [comment]
Maybe I'm not understanding the issue here but it sounds to me like your custom function should NOT return null for argument names. It should return a list of the 9 expected arguments names.

**Comment by mbosecke** [comment]
I.e., it should look like this:

    public MyURLBuildingFunction implements Function() {

        @Override
        public List<String> getArgumentNames() {
            List<String> names = new ArrayList<>();
            names.put("year");
            names.put('month");
            names.put('name");
            ...
            return names;
        }

        @Override
        public Object execute(Map<String,Object> args) {
            String year = (String)args.get("year");
            String month = (String)args.get("month");
            String name = (String)args.get("name");
            ...
        }
    }

**Comment by hectorlf** [comment]
Arguments are neither fixed in number nor in name. Let me try to clarify it:

In my app, have this 2 actions:
```
@UrlBinding("/archive/{year}/{month}/{name}")
public class ArchiveAction implements ActionBean { ... }

@UrlBinding("/pages/{title}")
public class PagesAction implements ActionBean { ... }
```
What i'm trying to achieve is a function that lets me accommodate some required arguments and an unknown number of optional and "user-defined" arguments. Something like:
```
{{ stripesUrl( class="com.foobar.ArchiveAction", year="2015", month="2", name="mypost" ) }}

{{ stripesUrl( class="com.foobar.PagesAction", title="mypage") }}
```
And that should print:
/contextPath/archive/2015/2/mypost
/contextPath/pages/mypage

ExpressionParser already does the dirty job, because arguments are parsed as named arguments irrespective of function's argumentNames list. But then, ArgumentsNode.getArgumentMap ignores the namedArgs list and only parses the positionalArgs, resulting in a empty function invocation.

Eg. the result of {{ max( number1=100, number2=200 }} is 0

**Comment by hectorlf** [comment]
Compatibility-wise, as far as my understanding of Pebble goes, the only thing that may break are misused functions/filters/tests that were silently broken before.

**Comment by mbosecke** [comment]
A consequence of what you're proposing is that functions would no longer have to explicitly declare what arguments they require; we would get rid of the `getArgumentNames` method in the `Function` interface entirely. One problem with that is the is that the Pebble engine would no longer have the ability to report errors to users when they accidentally use the wrong argument name (ex. typo).

Perhaps a better solution would be to add support for arrays and maps into the pebble syntax, similar to how [Twig](http://twig.sensiolabs.org/doc/templates.html#literals) does it.

In that case, your Function implementation would look like this:

    public MyURLBuildingFunction implements Function() {
        @Override
        public List<String> getArgumentNames() {
            List<String> names = new ArrayList<>();
            names.put("class");
            names.put("pathSegments");
            return names;
        }

        @Override
        public Object execute(Map<String,Object> args) {
            String className = (String)args.get("class");
            Map<String,String> pathSegments = (Map<String,String>)args.get("pathSegments");
            ...
        }
    }

and to invoke your function within the pebble template it might look like this:

    set segments = {"year" : "2015", "month" : "2", "name" : "mypost"}
    {{ stripesUrl( class="com.foobar.ArchiveAction", pathSegments=segments) }}

Unfortunately this will be a lot more work.

**Comment by mbosecke** [comment]
Another workaround (and it's not necessarily pretty but could be used as a temp solution) for your particular use case is for your Function to mandate that arguments are provided by the template in the exact order that they are used in the URL, with the "class" always being first. Drop the names and just rely on order.

**Comment by hectorlf** [comment]
I like the idea of array/map definitions, and that would nicely solve my needs. I've forked and started tinkering with an implementation for it just for fun, and it's daunting. If I get to something usable, i'll let you know.

**Comment by hectorlf** [comment]
Sorry to bring this back to life. I have an implementation for the array/map support in a feature branch. May I send a pull request?

**Comment by mbosecke** [comment]
Absolutely! I'd love to see it. I opened a new dedicated task for this, #68, because it's something I would love to see implemented.
