### ISSUE TITLE
Pebble on JDK6

### ISSUE THREAD

**Issue by golgoth14** [mbosecke/pebble#67]
Hello,

Is Pebble could run under JDK 6 ?
Is a Maven artifact with jdk6 classifier available ?

Thank you.
Steve

**Comment by mbosecke** [comment]
Hi Steve. Unfortunately no, Pebble has not been tested or built against JDK6 at all. At this time it is only compatible with 7 and 8.  I also don't think we'll ever make it compatible with JDK6; there simply isn't enough incentive.

**Comment by golgoth14** [comment]
Hi, Thank for your answer. Hope I will soon use JDK7 on my project...
