### ISSUE TITLE
Support of array/map syntax

### ISSUE THREAD

**Issue by mbosecke** [mbosecke/pebble#68]
The idea for this task was first brought up in #65.

We want to add support for arrays and maps into the pebble syntax similar to how [Twig](http://twig.sensiolabs.org/doc/templates.html#literals) does it.

A custom function might look like this:

    public MyURLBuildingFunction implements Function() {
        @Override
        public List<String> getArgumentNames() {
            List<String> names = new ArrayList<>();
            names.put("class");
            names.put("pathSegments");
            return names;
        }

        @Override
        public Object execute(Map<String,Object> args) {
            String className = (String)args.get("class");
            Map<String,String> pathSegments = (Map<String,String>)args.get("pathSegments");
            ...
        }
    }
and invoking the function within the pebble template might look like this:

    set segments = {"year" : "2015", "month" : "2", "name" : "mypost"}
    {{ stripesUrl( class="com.foobar.ArchiveAction", pathSegments=segments) }}

**Comment by mbosecke** [comment]
Release in v1.5.0. Thanks again @hectorlf

**Comment by hectorlf** [comment]
Glad to help! Speaking of which, I've seen in other comments that you were thinking of a third-party contrib space. I have some extensions in the pipeline, and I'd like to share them (or if you will, absorb them into your projects).
