### ISSUE TITLE
path variable & js variable

### ISSUE THREAD

**Issue by ipeisong** [mbosecke/pebble#70]
can provide sth like @{/path/page.html} in thymeleaf to make the servlet root auto resolved?

also how to pass object into javascript variables? thanks.

**Comment by mbosecke** [comment]
Pebble doesn't provide anything out-of-the-box to auto resolve the context path of your web app. I suggest adding a global variable containing the context path and referencing it like so:
    
    <a href="{{contextPath}}/page.html">click here</a>

Also, whether you're generating HTML, CSS, JS, or any other textual output, Pebble can be used in exactly the same way. Generating javascript might look like this:

    <script>
        var userName = {{ user.firstName }};
        alert(userName);
    </script>

The only thing I would do different is making sure that your variables are being [escaped properly for the given context](http://mitchellbosecke.com/pebble/documentation/guide/escaping).
