### ISSUE TITLE
res path

### ISSUE THREAD

**Issue by alexzk1** [mbosecke/pebble#72]
I bound Pebbie with spark, so in result I will have standalone JAR

templates have such a pathes:
{% import "../../common/macroses" %}

That is working unpacked and fails when packed to JAR:
Could not find template "resources/theme1/views/../../common/macroses.html" (?:?)

I copied class resource loader with next fix., which goes as IDE/Tomcat/standalone jar:

String location = path.toString() + templateName + (getSuffix() == null ? "" : getSuffix());
        logger.debug("Looking for template in {}.", location);

        //this try is fix for jar
        try
        {
            location = new File("/",location).getCanonicalPath().substring(1);
        } catch (IOException e)
        {
            e.printStackTrace();
        }

        // perform the lookup

        ClassLoader rcl = ResLoader.class.getClassLoader();

**Comment by mbosecke** [comment]
I'm not sure I understand what's happening here. Does the code you provided solve the issue? If so, I suggest adding a unit test that demonstrates the issue and then submitting a pull request. If not, I have some questions to try and troubleshoot:

* What is the exact location of the file within the jar?
* What settings have you tried for the ClasspathLoader prefix?
* Have you tried using  the [ServletLoader](https://github.com/mbosecke/pebble/blob/master/src/main/java/com/mitchellbosecke/pebble/loader/ServletLoader.java)?

**Comment by alexzk1** [comment]
yes, it fixes. Path is like 
/resources
   |--common
         ...macroses here
   |--theme1
          |--views
               ....html files here

Oh yes...preffix set to views path.
public  final static String CURRENT_THEME="theme1";
    private final static String VIEWS = "resources/"+CURRENT_THEME+"/views/";
final Loader ldr = new ResLoader();
        ldr.setPrefix(VIEWS);

**Comment by mbosecke** [comment]
There was a recent pull request that changed the ClasspathLoader which [included a test](https://github.com/mbosecke/pebble/blob/master/src/test/java/com/mitchellbosecke/pebble/LoaderTest.java#L57) that pulls a template from a jar file. I believe this should fix the issues you were having. I'll be publishing a new version of pebble today; feel free to comment on this task if it still doesn't resolve your issue. Thanks.
