### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by eleumik** [mbosecke/pebble#78]
Hi,
I came here from the tests https://github.com/jreijn/spring-comparing-template-engines page.

I am interested in localization, I would like to plug different localization library, for example a Spring MessageSource implementation.

I looked into https://github.com/mbosecke/pebble/blob/master/src/main/java/com/mitchellbosecke/pebble/extension/i18n/i18nFunction.java and I saw it uses ResourceBundle retrieving a bundle for each message. 

I think it would be useful to extract this code and abstract it in an interface, so that any implementation can be plugged, something like in
http://www.displaytag.org/10/apidocs/org/displaytag/localization/package-summary.html
http://displaytag.sourceforge.net/11/displaytag/xref/org/displaytag/localization/I18nSpringAdapter.html

It would be also nice to allow to ask a localizable property without specifying the Bundle Name, as can be done with <fmt:message> or <spring:message>. Some implementations just load all the resources at app start, so there is no need to choose a specific bundle/resource, others (like one based on ResourceBundle ) might use a configurable "default bundle name", something like `javax.servlet.jsp.jstl.fmt.localizationContext` http://stackoverflow.com/a/12471064/1536382 

Thanks,
Michele

**Comment by hectorlf** [comment]
Pebble is ridiculously easy to extend, and i18nFunction is an example of an extension.

Put another way: Pebble is framework agnostic. It doesn't care what's below or how it's invoked, and whenever you need to integrate with something specific (like Spring MVC), it's better to think of that as an extension point.

I've been planning such extension for a bit, but I don't have anything to share yet ;-/

**Comment by UshakovVasilii** [comment]
Hi, you can use https://github.com/asaas/pebble-spring-translate
Extension use MessageSource

**Comment by eleumik** [comment]
Thanks guys, I think now I have got a better picture.
