### ISSUE TITLE
Bad error handling on method invocation

### ISSUE THREAD

**Issue by ethlo** [mbosecke/pebble#81]
In https://github.com/mbosecke/pebble/blob/0d13fdd028ab636e2253e7139d1d43a19ebc6395/src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java#L174 I see this code 
```java
} catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
            e.printStackTrace();
}
```
This does not play well on non-interactive consoles, like in a web-server. Consider throwing an unchecked exception if in strict mode, otherwise return null/empty.

**Comment by mbosecke** [comment]
Good find.

I decided to throw the exception regardless if running in strict mode or not; it's too important of an exception that I don't think any one would want it ignored.
