### ISSUE TITLE
Bean reflection doesn't check parent class

### ISSUE THREAD

**Issue by decebals** [mbosecke/pebble#84]
I have a `CompanyService` with a method `get(long id):Company`, I injected the `companyService` in my template model and I I try something like this:
```
{% for customer in customers %}
<tr>
   <td>{{ companyService.get(customer.companyId) }}</td>
</tr>
{% endfor %}
```
where `Customer` has a property `Long companyId` (my idea is to create a quick prototype of application without a fat `CustomerDto` that contains a `Company`).
The result is an empty ("") string without any message in console.
Any idea?

**Comment by decebals** [comment]
Anybody?
I want to continue to use this excellent library but without a minimal support I cannot go forward.

**Comment by UshakovVasilii** [comment]
I think empty string is possible if `companyService.get(customer.companyId)` is null or `toString` method return empty string.
please check the following:
`<td>{{ companyService.get(customer.companyId) is null }}</td>`
`<td>{{ companyService.get(customer.companyId).toString() is empty }}</td>`

**Comment by jcarvalho** [comment]
If any of those fail, you can also fire up the Debugger, and break on 
PrintNode's render method.

This way you will be able to track your method invocation and see the 
returned value.

**Comment by decebals** [comment]
After some debugging I can say that problems is [here](  https://github.com/mbosecke/pebble/blob/c98cba4e0b2d1d354dce79bf3a6ded3e412b612a/src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java#L258). My method `customerService.get(Long id)` is not found and I don't know why.
In my opinion pebble must throw an warning message in console if it not found a method, because it's very hard to debug this kind of problems.

**Comment by jcarvalho** [comment]
Perhaps there is an issue with primitive types?

According to your original issue, your `get` method receives a primitive `long`, whereas your `getCompanyId` method returns a boxed `Long`. I don't believe Pebble automatically takes care of that conversion.

**Comment by decebals** [comment]
I changed my `companyService.get(long id)` to `companyService(Long id)` because I feel that pebble is not prepared for this :smile: 

My test is very simple.
`PebbleTest.java`
```
public static void main(String[] args) {
    List<Company> companies = new ArrayList<>();
    companies.add(new Company(1) // id
        .setName("decisoft")
        .setFiscalCode("111111111"));
    CompanyService companyService = new InMemoryCompanyService(companies);

    PebbleEngine engine = new PebbleEngine();
    try {
        PebbleTemplate compiledTemplate = engine.getTemplate("templates/test.peb");
        Writer writer = new StringWriter();

        Map<String, Object> context = new HashMap<>();
        context.put("companyService", companyService);
        compiledTemplate.evaluate(writer, context);

        String output = writer.toString();
        System.out.println("output = " + output);
    } catch (PebbleException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }
}
```

and `test.peb` is:
```
<!DOCTYPE html>
<html>
    <head>
        <title>Pebble Test</title>
    </head>

    <body>
        <!--
        <span>{{ companyService.get(1) }}</span>
        -->
        <span>{{ companyService.getByFiscalCode("111111111") }}</span>
    </body>
</html>
```

The result is: 
- `{{ companyService.getByFiscalCode("111111111") }}` WORKS
- `{{ companyService.get(1) }}` DOESN"T WORK

Has anyone tried to use a parameter with type number/long?

**Comment by decebals** [comment]
I found where is the problem. The problem is the same founded by me [here](https://github.com/decebals/pippo/issues/206).
In a sentence the `get()` method is a method from a superclass that it's not found with the current pebble implementation `clazz.getMethod(attributeName, parameterTypes);`
So, `InMemoryCompanyService` is a class that extends `InMemoryGenericService`.
In conclusion I think that it's a bug in pebble.
Can someone fix this issue, please?

**Comment by decebals** [comment]
I have the same problem if I try to use `{{ companies.get(customer.companyId) }}` or most simple `{{ companies.get(1) }}` where `companies` variable is a `Map<Long, Company>`.

**Comment by mbosecke** [comment]
That makes sense that it wouldn't find inherited fields or methods; I would consider this a bug. It will have to recursively check parent classes until it hits the `Object` class. Hopefully I'll have a chance next week to take a closer look.

**Comment by mbosecke** [comment]
Sorry for the delay on this one. I wrote a simple test case and I think our original assumption is wrong, it DOES currently find parent fields and methods. I'm using [class.getMethod](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getMethod-java.lang.String-java.lang.Class...-) which is documented to recursively look at parent classes.

Are you able to create a small test case that I can use to reproduce the error?

**Comment by decebals** [comment]
I cannot reproduce the issue in a quick start. Indeed if I try something simple everything is OK but in my real application I used a [generic-dao](https://github.com/decebals/dada) with multiple inheritance and the problem persist. I will close this issue and if I find something useful I will reopen it.

**Comment by decebals** [comment]
I created a quick start [here](https://github.com/decebals/pebble-test). Maybe someone take a look and find where is the problem. Thanks!

**Comment by mbosecke** [comment]
I just made a [commit](https://github.com/mbosecke/pebble/commit/eda9f01b915ae07f39e65a27be04f10810786538) that I believe fixes your issue. This commit changes the way Pebble looks for methods; it's much more relaxed when comparing argument types. If you get a chance to confirm the fix, that'd be great.

**Comment by decebals** [comment]
I confirm that your commit resolves the issue.
