### ISSUE TITLE
On Glassfish: com.mitchellbosecke.pebble.error.LoaderException: Could not find template "home.html"

### ISSUE THREAD

**Issue by pdurbin** [mbosecke/pebble#86]
Similar to #54 but for Glassfish, I haven't been able to figure out easily how to have Pebble find my templates. From https://github.com/mbosecke/pebble#basic-usage it seems like `src/main/webapp/WEB-INF/home.html` is the right place (and I've tried various paths) but I get the exception below when I try:

`PebbleTemplate compiledTemplate = engine.getTemplate("home.html");`

Here's the exception:

```
[2015-08-13T08:50:03.074-0400] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=29 _ThreadName=http-listener-1(1)] [timeMillis: 1439470203074] [levelValue: 900] [[
  StandardWrapperValve[default]: Servlet.service() for servlet default threw exception
com.mitchellbosecke.pebble.error.LoaderException: Could not find template "home.html" (?:?)
	at com.mitchellbosecke.pebble.loader.DelegatingLoader.getReader(DelegatingLoader.java:64)
	at com.mitchellbosecke.pebble.PebbleEngine$1.call(PebbleEngine.java:188)
	at com.mitchellbosecke.pebble.PebbleEngine$1.call(PebbleEngine.java:177)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4796)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3589)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2374)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2337)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2252)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3990)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4793)
	at com.mitchellbosecke.pebble.PebbleEngine.getTemplate(PebbleEngine.java:177)
``` 

It works when I use this but obviously I don't want to keep my templates in "/tmp":

`PebbleTemplate compiledTemplate = engine.getTemplate("/tmp/home.html");`

If there is a method to help me troubleshoot were Pebble is looking I haven't been able to find it. Maybe I need to do some configuration similar to https://github.com/mbosecke/pebble-example-spring/blob/51a485740e253241265f8fc59b34c74680ed305f/src/main/java/com/example/config/MvcConfig.java ? Not sure.

**Comment by mbosecke** [comment]
Sorry for the delay on this; you've probably already figured out your problem. The stack trace is telling me that you are using the default Loader class to find your templates (DelegatingLoader); I suggest switching that to the [ServletLoader](https://github.com/mbosecke/pebble/blob/master/src/main/java/com/mitchellbosecke/pebble/loader/ServletLoader.java). The servlet loader uses the ServletContext to find your templates which works well in application servers.

By default the DelegatingLoader delegates responsibility to the [FileLoader](https://github.com/mbosecke/pebble/blob/master/src/main/java/com/mitchellbosecke/pebble/loader/FileLoader.java) and then the [ClasspathLoader](https://github.com/mbosecke/pebble/blob/master/src/main/java/com/mitchellbosecke/pebble/loader/ClasspathLoader.java).

**Comment by pdurbin** [comment]
@mbosecke thanks! Yes, if I put my templates in `src/main/webapp/WEB-INF/templates` and specify the ServletLoader like this...

```
@Path("pebble")
public class PebbleTest {

    @Context
    private ServletContext servletContext;

    @GET
    @Path("test")
    public String test() throws PebbleException, IOException {

        PebbleEngine engine = new PebbleEngine();
        ServletLoader servletLoader = new ServletLoader(servletContext);
        servletLoader.setPrefix("/WEB-INF/templates");
        engine.setLoader(servletLoader);

        PebbleTemplate compiledTemplate = engine.getTemplate("home.html");
        Map<String, Object> context = new HashMap<>();
        context.put("name", "Mitchell");

        Writer writer = new StringWriter();
        compiledTemplate.evaluate(writer, context);
        String output = writer.toString();
        return output;
    }

}
```

... the example in the readme at https://github.com/mbosecke/pebble seems to work fine:

```
[pdurbin@tabby javaee7]$ curl http://localhost:8080/javaee7/api/pebble/test
<html>
<head>
    <title> Home </title>
</head>
<body>
    <div id="content">
            <h1> Home </h1>
    <p> Welcome to my home page. My name is Mitchell.</p>
    </div>
    <div id="footer">
                    Copyright 2014
            </div>
</body>
</html>
```

http://www.mitchellbosecke.com/pebble/documentation/guide/installation says "ServletLoader : Uses a servlet context to find the template. This is the only built in loader that will work with JBoss/Wildfly but is not enabled by default." Maybe you could add Glassfish to the list.

**Comment by mbosecke** [comment]
Yes, I'll keep this issue open until I update the documentation. Thanks

**Comment by prasad83** [comment]
engine.setLoader - was not possible. But had to initialize builder with loader 
Following sequence worked for me...

```java
protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
            ServletLoader servletLoader = new ServletLoader(req.getServletContext());
            servletLoader.setPrefix("/WEB-INF/templates");
            PebbleEngine.Builder builder = new PebbleEngine.Builder().loader(servletLoader);
            PebbleEngine engine = builder.build();
            ...
```
