### ISSUE TITLE
Minify extension based on htmlcompressor?

### ISSUE THREAD

**Issue by gitblit** [mbosecke/pebble#88]
It would be handy to have an extension to allow template minification.  Trimou, for example, uses htmlcompressor. https://code.google.com/p/htmlcompressor/

**Comment by mbosecke** [comment]
Good idea; I'm definitely a proponent.

I'll be keeping this task open; hopefully my lazy ass will start on it pretty soon but no promises.

**Comment by gitblit** [comment]
@mbosecke Sounds good.  BTW, I love Pebble!  Keep up the good work!

**Comment by mbosecke** [comment]
I started a new repository for pebble extensions that don't quite belong in the core and I think this would be a good example so I'm closing this task from this repository.
