### ISSUE TITLE
Provide setting for custom HTML escape. This will remove co-verity api dependency!

### ISSUE THREAD

**Issue by haducloc** [mbosecke/pebble#89]
Google guava already provide awesome HTML escape so why coverity? Custom interface for HTML escape even better. Thanks!

**Comment by mbosecke** [comment]
I'm not overly familiar with Guava's escaping functionality but after taking a quick glance it looks like it only supports basic HTML escaping. Coverity on the other hand supports multiple escape contexts such as:
* HTML
* HTML attributes
* Javascript strings
* URL parameters

If I switched to guava's escaping library I'd lose some functionality. If anything, I want to remove the google guava dependency; Pebble uses very little of what guava is capable of so it's kind of overkill at this point.

**Comment by decebals** [comment]
On 1 Sep 2015 04:37, "Mitchell Bösecke" <notifications@github.com> wrote:
>
> I'm not overly familiar with Guava's escaping functionality but after
taking a quick glance it looks like it only supports basic HTML escaping.
Coverity on the other hand supports multiple escape contexts such as:
>
> HTML
> HTML attributes
> Javascript strings
> URL parameters
>
> If I switched to guava's escaping library I'd lose some functionality. If
anything, I want to remove the google guava dependency; Pebble uses very
little of what guava is capable of so it's kind of overkill at this point.
+1

**Comment by haducloc** [comment]
What I mean is dependency of co-verity should be removed. Use Google guava or any other libs depends on devs. What if devs has better escapes api? So If we provide custom escape interfaces, this will be better!

**Comment by mbosecke** [comment]
I am a proponent of adding an API for users to provide a custom escaper in order to support more contexts, so for that reason I'll keep this task open. I won't be removing coverity though, Pebble needs out-of-the-box escaping capabilities.

Thanks for the idea.
