### ISSUE TITLE
Exception throw on pebbleEngine.getTemplate() shoud be RuntimeException

### ISSUE THREAD

**Issue by haducloc** [mbosecke/pebble#90]
The exception is checked exception type. It forces adding try/catch. This is inconvenient for devs. Use RuntimeException is better & more suitable for this situation. Thanks!

**Comment by mbosecke** [comment]
I disagree. Here's why:

* In any given project there is typically only one single call to `getTemplate()` therefore this is not a continuous drag on the developer.
* There are many escape routes a developer could take if a template fails to be found/compiled. They could redirect to a different template, send out an email report, etc. It is the intention of the Pebble library that a developer will account for this.
* There are set ups where the main dev is not the same person who is writing the templates. This scenario is an open system where failure is inevitable; I think that's a great use case for a checked exception.
* If the dev is really lazy, they can just wrap the one checked exception in a RuntimeException.

**Comment by haducloc** [comment]
OK. You have your points. I have used Velocity templates before. They designed org.apache.velocity.exception.ParseErrorException & org.apache.velocity.exception.ResourceNotFoundException are Runtime exception. I found this exception design is suitable for getting compiled template context.

If you use Runtime exception, developers still able to try/catch the exception and handle the logic.

**Comment by mbosecke** [comment]
It can be debated either way. I don't think we'll change it at this time but it's something that we'll definitely revisit for a version 2 of Pebble.
