### ISSUE TITLE
Delegating loader issue

### ISSUE THREAD

**Issue by gjeraj** [mbosecke/pebble#91]
Delegating loader always loads template from the last loader in the list. Should be something like this:

    for (Loader loader : this.loaders) {
        try {
            reader = loader.getReader(templateName);

            if (reader != null)
                return reader;
        } catch (LoaderException e) {
            // do nothing
        }
    }

**Comment by mbosecke** [comment]
Holy smokes, I can't believe that went unnoticed/untested for so long. This definitely needs to be fixed, thanks.
