### ISSUE TITLE
Add a method into EvaluationContext that can be used to evaluate an expression in Function, Filter, Test, or Parser

### ISSUE THREAD

**Issue by haducloc** [mbosecke/pebble#92]
For some reasons, Developers will pass Expressions as Func/Test/Filter arguments and evaluate the expressions depends on some code logic. (JSP/JSTL/EL support this feature)

Propose spec:

EvaluationContext ctx = (EvaluationContext)args.get("_context");
		
// String expression = "variableName.prop1.prop11";	
String expression = (String) args.get("expression");
		
Object value = ctx.evaluate(expression);

Thank you very much!

**Comment by mbosecke** [comment]
Pebble already allows expressions as arguments and will automatically parse them for you. For example, this is already do-able in Pebble:

  {{ myFunction(var.prop1.prop11) }}

And the "myFunction" would receive the parsed result. It would NOT receive "var.prop1.prop11" but would instead receive the actual property value. This is already implemented so I don't see a need for anyone to have to manually parse anything.
