### ISSUE TITLE
["role1", "role2"] evaluated as ArrayList, not array as expected

### ISSUE THREAD

**Issue by haducloc** [mbosecke/pebble#93]
My function code:

    public class AuthorizeFunction implements Function {

	public static final String ARG_USER_ROLES = "userRoles";

	final List<String> argumentNames = Arrays.asList(ARG_USER_ROLES);

	@Override
	public List<String> getArgumentNames() {
		return this.argumentNames;
	}

	@Override
	public Object execute(Map<String, Object> args) {
		String[] roles = (String[]) args.get(ARG_USER_ROLES);
                // Throw exception because args.get(ARG_USER_ROLES) is ArrayList instance
		return true;
	}
    }

My use:

    {% if authorize( ["role1", "role2"] ) %}
        authorized
    {% endif %}

**Comment by mbosecke** [comment]
Yes, Pebble will parse `["role1", "role2"]` as a `List`. I see that the documentation could use a little clarification which I'll do. So in this case you would simply change your function to use the following line:

    List<String> roles = (List<String>) arg.get(ARG_USER_ROLES);

**Comment by haducloc** [comment]
Thank you!

**Comment by mbosecke** [comment]
No problem! I'll keep this task open as a reminder to myself to update the documentation.
