### ISSUE TITLE
Else if documentation inconsistent/wrong

### ISSUE THREAD

**Issue by hankditton** [mbosecke/pebble#98]
On the "basic-usage" page (http://www.mitchellbosecke.com/pebble/documentation/guide/basic-usage) the example for the if statement shows "else if" as two separate words, but then in the description of the "if" tag (http://www.mitchellbosecke.com/pebble/documentation/tag/if) it shows it as one word.

**Comment by chrisgavinme** [comment]
I've just run across this too. For the benefit of people who might try and Google the stack trace when using "else if":

```com.mitchellbosecke.pebble.error.ParserException: Unexpected token of value "if" and type NAME, expected token of type EXECUTE_END
	at com.mitchellbosecke.pebble.lexer.TokenStream.expect(TokenStream.java:92)
	at com.mitchellbosecke.pebble.lexer.TokenStream.expect(TokenStream.java:60)
	at com.mitchellbosecke.pebble.tokenParser.IfTokenParser.parse(IfTokenParser.java:50)```

**Comment by mbosecke** [comment]
Documentation has been fixed; thank you!
